### ISSUE TITLE
Error 14 while sending SysEx

### ISSUE THREAD

**Issue by Kreczek** [justlep/bitwig#5]
BCF reports multiple Error 14 "Meaning: Invalid number of arguments (too few or too many)." while sending Sysex to device (in my case using MIDI-OX).
Anyway preset is working with Bitwig. 
Script Version 1.0.7

**Comment by justlep** [comment]
My BCF showed the same error during the sysex transfer, but the preset works fine nonetheless, as you said. I used Behringer's B-Control Editor v0.2 beta 3 to generate the file. The editor hasn't seen updates in years, so I'm afraid we'll just have to live with the weird "error". Fortunately, it's a once-in-a-lifetime transfer only.

However, as it is quite irritating, I'll add a notice on this issue to the documentation.

**Comment by Kreczek** [comment]
OK ,so I purged your sysEx file from errors via BC edit.
https://gist.github.com/Kreczek/f6b93c07c232ed6f88ea#file-bcf2000-bitwig-preset28-ch13-_purged-syx

**Comment by justlep** [comment]
Your file gave me the needed hint as I saw you were using BC Manager instead of Behringer's old BCEdit to generate it. Thank you very much!

I just re-generated my sysex file with the two presets 28/29 via BC Manager. Now the file works perfectly and without ER14 messages during transfer! Great! 

The fixed .syx file is contained in the new v1.0.8 zip package in the downloads directory.
Again, thanks very much for your help!
